contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/uninsured-vesting-v1/UninsuredVestingV1.sol
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts
test/uninsured-vesting-v1/fixture.ts
test/uninsured-vesting-v1/uninsured-vesting-v1.ts

Change period count into constant

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/insured-vesting-v1/readme.md
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

Use `setAllocation` rather than `addAllocation`

---

contracts/uninsured-vesting-v1/UninsuredVestingV1.sol
test/uninsured-vesting-v1/uninsured-vesting-v1.ts

Change uninsured addAmount to setAmount

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

27 make project settable again all transfers of tokens from and to should go there and not owner

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

only if not emergency released

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/insured-vesting-v1.test.ts

toggle only if you funded the contract

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/insured-vesting-v1.test.ts

```
File                     |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------|----------|----------|----------|----------|----------------|
insured-vesting-v1/     |      100 |    98.57 |      100 |      100 |                |
InsuredVestingV1.sol   |      100 |    98.57 |      100 |      100 |                |
test/                   |      100 |      100 |      100 |      100 |                |
MockERC20.sol          |      100 |      100 |      100 |      100 |                |
MockUSDC.sol           |      100 |      100 |      100 |      100 |                |
uninsured-vesting-v1/   |    96.67 |    93.75 |      100 |      100 |                |
UninsuredVestingV1.sol |    96.67 |    93.75 |      100 |      100 |                | …
```

38 ensure test coverage

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/uninsured-vesting-v1/UninsuredVestingV1.sol
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts
test/uninsured-vesting-v1/fixture.ts
test/uninsured-vesting-v1/uninsured-vesting-v1.test.ts

Add more tests for recover in uninsured, clean up test structure, misc

---

.github/workflows/pull_request.yml
.solhint.json
contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/test/MockERC20.sol
contracts/test/MockUSDC.sol
contracts/uninsured-vesting-v1/UninsuredVestingV1.sol
package-lock.json
package.json

Add solhint, fix lint issues

---

deployment/insured-vesting-v1/config.ts
hardhat.config.ts
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

Add deployment script and prod config for insured vesting contract

---

deployment/uninsured-vesting-v1/config.ts
hardhat.config.ts
test/uninsured-vesting-v1/fixture.ts
test/uninsured-vesting-v1/uninsured-vesting-v1.test.ts

Add deployment script and prod config for uninsured vesting contract

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

removed minimum funding amount required

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/uninsured-vesting-v1/UninsuredVestingV1.sol
deployment/insured-vesting-v1/config.ts
deployment/uninsured-vesting-v1/config.ts
test/insured-vesting-v1/deployment.test.ts
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

pass in vesting period in constructor

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
deployment/insured-vesting-v1/config.ts
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

removed decimals usage within contract

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/uninsured-vesting-v1/UninsuredVestingV1.sol
deployment/insured-vesting-v1/config.ts
deployment/insured-vesting-v1/script.ts
test/insured-vesting-v1/deployment.test.ts
test/insured-vesting-v1/fixture.ts
test/insured-vesting-v1/insured-vesting-v1.test.ts

83 insured token precision changes

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/insured-vesting-v1.test.ts

added view functions

---

contracts/vesting-v1/VestingV1.sol
deployment/vesting-v1/config.ts
deployment/vesting-v1/script.ts
test/uninsured-vesting-v1/deployment.test.ts
test/uninsured-vesting-v1/fixture.ts
test/uninsured-vesting-v1/uninsured-vesting-v1.test.ts

Updates to vesting contract + tests to use ownables for roles instead of Access Control
Closes #86

Updates to vesting contract to work with new project role ownable

---

contracts/vesting-v1/VestingV1.sol
test/vesting-v1/vesting-v1.test.ts

uninsured - remove delta transfer logic on activate()

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
test/insured-vesting-v1/insured-vesting-v1.test.ts

insured - remove delta transfer logic on activate()

---

contracts/insured-vesting-v1/InsuredVestingV1.sol
contracts/vesting-v1/VestingV1.sol
test/insured-vesting-v1/insured-vesting-v1.test.ts
test/vesting-v1/vesting-v1.test.ts

remove onlyifnotemergencyreleased from claim()

---

contracts/roles/ProjectRole.sol
contracts/vesting-v1/VestingV1.sol

Fix solhint warnings
